### ISSUE TITLE
DyLoRA選択時の --network_args について

### ISSUE THREAD

**Issue by zaknak** [RedRayz/Kohya_lora_param_gui#14]
https://github.com/RedRayz/Kohya_lora_param_gui/blob/4ef97f16c502716bf607de6301f733631435c98d/Kohya_lora_trainer/MyUtils.cs#L94

"unit=" とするのが正しいと思われます。"unit " では学習に入る段階でエラーとなります。

**Comment by RedRayz** [comment]
ご報告ありがとうございます。エラーが確認できたため修正しました。修正は次回のリリースで反映されます。
