### ISSUE TITLE
RedRayzさんへ：1)TrainTrainキャプションタグ形式：2)seed制限

### ISSUE THREAD

**Issue by muooon** [RedRayz/Kohya_lora_param_gui#27]
Guiの外観もキレイになって使い易さもパワーアップしてすごい(いつも感謝ですありがとう)
さて機能追加について要望してみても良いでしょうか？

1, TrainTrainで｢ファイル名｣でキャプション(タグ)できますこの形式にもご対応いただけるとタグ付けが楽しくできそうです
参考例：｢cap1, cap2, 3, 4, ,,, \_ID_ (ID以降無視).拡張子｣
この形式だと Windows の PowerTOOLs PowerRename 等で簡単に一括タグ付け可能になります｢,｣カンマ区切りと \_ID_ 以降無視のルールなので元ファイル名を揃えたりもなく簡易なキャプ付け方法としていかがでしょうか？
2,Guiのパラメータ、Seed値の上限をなくせるならなくして欲しいです(json形式による制限のようですが…)

以上の２つ要望です(お時間あるときに叶えて頂けたら幸いです)

**Comment by muooon** [comment]
訂正：上記 _ID_ 部分は、
｢\_ID_\｣です(これで記号入力可能かな？) アンダーバーIDアンダーバー
(失礼しました)

**Comment by RedRayz** [comment]
すみません、1のほうは対応しません。
2のほうはlongの範囲まで拡張してみます。

**Comment by muooon** [comment]
お忙しい中さっそくのご返答とご対応を頂きありがとうございました。これからもこの便利なツールを使わせて頂きます。益々のご発展を祈りお礼とさせてください。どうもありがとうございました！

**Comment by muooon** [comment]
RedRayzさん、取り急ぎですが、seed上限の拡張ありがとうございました！早速1.9.0.0を試し今は1.9.0.1を試すところです。
別の話です、PagedLion8bit軽くていいですね！3600_12GBだとLatentキャッシュ(DISK)環境下で12バッチで回せます。PONY系の学習にも効果的なオプティマイザのようで重宝してます。最新オプティマイザも使えて最強ツールです♫(npz消去も便利でステキです) 
使用しての感想等を記す場所ではないような気もしますが｢ありがとう｣のヒトコトでは済まないほどの感謝をどうしても伝えたく今回だけご容赦ください。本当にありがとうございました。
