### ISSUE TITLE
returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by lemoneder** [RedRayz/Kohya_lora_param_gui#28]
トレーニング途中で落ちてしまいます。

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory C:\gazo\mrn\5_mrn contains 654 image files
3270 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (1024, 1024)
  enable_bucket: True
  network_multiplier: 1.0
  min_bucket_reso: 320
  max_bucket_reso: 1536
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\gazo\mrn\5_mrn"
    image_count: 654
    num_repeats: 5
    shuffle_caption: True
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: mrn
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 654/654 [00:00<00:00, 1250.94it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (1344, 768), count: 3270
mean ar error (without repeats): 0.027777777777777676
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:\sd2\webui\models\Stable-diffusion\animagineXLV3_v30.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████| 654/654 [00:00<00:00, 1031.52it/s]
caching latents...
0it [00:00, ?it/s]
create LoRA network. base dim (rank): 8, alpha: 3.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
apply LoRA to Conv2d with kernel size (3,3). dim (rank): 4, alpha: 1.0
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 788 modules.
enable LoRA for U-Net
prepare optimizer, data loader etc.
bin C:\redrayz\sd-scripts\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
use 8-bit AdamW optimizer | {}
override steps. steps for 8 epochs is / 指定エポックまでのステップ数: 13080
enable fp8 training.
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 3270
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1635
  num epochs / epoch数: 8
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 13080
steps:   0%|                                                                                 | 0/13080 [00:00<?, ?it/s]
epoch 1/8
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
C:\redrayz\sd-scripts\venv\lib\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\redrayz\sd-scripts\venv\lib\site-packages\torch\utils\checkpoint.py:61: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
steps:  12%|██████▌                                             | 1635/13080 [22:20<2:36:23,  1.22it/s, avr_loss=0.114]
epoch 2/8
steps:  20%|██████████▏                                         | 2570/13080 [35:05<2:23:30,  1.22it/s, avr_loss=0.114]Traceback (most recent call last):
  File "C:\Users\lemon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lemon\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\redrayz\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\redrayz\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\redrayz\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\redrayz\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\redrayz\\sd-scripts\\venv\\Scripts\\python.exe', 'sdxl_train_network.py', '--pretrained_model_name_or_path', 'C:\\sd2\\webui\\models\\Stable-diffusion\\animagineXLV3_v30.safetensors', '--train_data_dir', 'C:\\gazo\\mrn', '--output_dir', 'C:\\sd2\\webui\\models\\Lora', '--network_module', 'networks.lora', '--network_args', 'conv_dim=4', 'conv_alpha=1', '--xformers', '--gradient_checkpointing', '--persistent_data_loader_workers', '--cache_latents', '--cache_latents_to_disk', '--max_data_loader_n_workers', '1', '--enable_bucket', '--save_model_as', 'safetensors', '--lr_scheduler_num_cycles', '4', '--mixed_precision', 'fp16', '--learning_rate', '0.0001', '--resolution', '1024', '--train_batch_size', '2', '--max_train_epochs', '8', '--network_dim', '8', '--network_alpha', '3', '--shuffle_caption', '--optimizer_type', 'AdamW8bit', '--lr_warmup_steps', '250', '--output_name', 'mrn4', '--save_precision', 'fp16', '--lr_scheduler', 'cosine_with_restarts', '--min_bucket_reso', '320', '--max_bucket_reso', '1536', '--caption_extension', '.txt', '--seed', '42', '--network_train_unet_only', '--noise_offset', '0.1', '--fp8_base']' returned non-zero exit status 3221225477.

**Comment by RedRayz** [comment]
returned non-zero exit status 3221225477より下にもエラーメッセージが出ているはずなので、載せていただけると原因がわかるかもしれません。

**Comment by RedRayz** [comment]
学習が途中まで進んでいるようですので、GUIが原因では無いと思われます。
