### ISSUE TITLE
caching latents...でエラーが出てしまう

### ISSUE THREAD

**Issue by ttyksi** [RedRayz/Kohya_lora_param_gui#36]
当方非エンジニアのためエラーの特定のために必要な情報が不足しているかもしれませんが、画面上に表示された全文を載せます
Python 3.10.6とgitはインストール済みでGUI付属の機能でsd-scriptsをインストールしました
データセットを過去に正常にLoraを作成できたものに変更しましたが同じ状態です
何が原因だと考えられますでしょうか
バージョンは1.11.1.0と1.11.0.2で試しましたが同じでした

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-04-13 22:53:19 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
2024-04-13 22:53:20 INFO     Using DreamBooth method.                                               train_network.py:172
                    INFO     prepare images.                                                          train_util.py:1572
                    INFO     found directory F:\Lorafabric\dataset\2_38 contains 415 image files      train_util.py:1519
                    INFO     830 train images with repeating.                                         train_util.py:1613
                    INFO     0 reg images.                                                            train_util.py:1616
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1621
                    INFO     [Dataset 0]                                                              config_util.py:565
                               batch_size: 2
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 512
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: False

                               [Subset 0 of Dataset 0]
                                 image_dir: "F:\Lorafabric\dataset\2_38"
                                 image_count: 415
                                 num_repeats: 2
                                 shuffle_caption: True
                                 keep_tokens: 1
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: 38
                                 caption_extension: .txt

                    INFO     [Dataset 0]                                                              config_util.py:571
                    INFO     loading image sizes.                                                      train_util.py:853
100%|██████████████████████████████████████████████████████████████████████████████| 415/415 [00:00<00:00, 2074.29it/s]
                    INFO     make buckets                                                              train_util.py:859
                    INFO     number of images (including repeats) /                                    train_util.py:905
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (768, 1280), count: 2                                train_util.py:910
                    INFO     bucket 1: resolution (832, 1216), count: 180                              train_util.py:910
                    INFO     bucket 2: resolution (896, 1152), count: 2                                train_util.py:910
                    INFO     bucket 3: resolution (1024, 1024), count: 16                              train_util.py:910
                    INFO     bucket 4: resolution (1088, 960), count: 16                               train_util.py:910
                    INFO     bucket 5: resolution (1216, 832), count: 614                              train_util.py:910
                    INFO     mean ar error (without repeats): 0.04053863524597019                      train_util.py:915
                    INFO     preparing accelerator                                                  train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:30
                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:70
                             F:\StabilityMatrix-win-x64\Data\Models\StableDiffusion\ponyDiffusionV
                             6XL_v6StartWithThisOne.safetensors
2024-04-13 22:53:21 INFO     building U-Net                                                       sdxl_model_util.py:192
                    INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
2024-04-13 22:53:36 INFO     U-Net: <All keys matched successfully>                               sdxl_model_util.py:202
                    INFO     building text encoders                                               sdxl_model_util.py:205
                    INFO     loading text encoders from checkpoint                                sdxl_model_util.py:258
2024-04-13 22:53:37 INFO     text encoder 1: <All keys matched successfully>                      sdxl_model_util.py:272
2024-04-13 22:53:40 INFO     text encoder 2: <All keys matched successfully>                      sdxl_model_util.py:276
                    INFO     building VAE                                                         sdxl_model_util.py:279
                    INFO     loading VAE from checkpoint                                          sdxl_model_util.py:284
                    INFO     VAE: <All keys matched successfully>                                 sdxl_model_util.py:287
                    INFO     load VAE:                                                                model_util.py:1268
                             F:\StabilityMatrix-win-x64\Data\Models\VAE\sdxl_vae.safetensors
2024-04-13 22:53:41 INFO     additional VAE loaded                                                sdxl_train_util.py:128
                    INFO     Enable xformers for U-Net                                                train_util.py:2660
import network module: networks.lora
2024-04-13 22:53:42 INFO     [Dataset 0]                                                              train_util.py:2079
                    INFO     caching latents.                                                          train_util.py:974
                    INFO     checking cache validity...                                                train_util.py:984
100%|█████████████████████████████████████████████████████████████████████████████| 415/415 [00:00<00:00, 59302.13it/s]
                    INFO     caching latents...                                                       train_util.py:1021
  0%|                                                                                          | 0/415 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\Lorafabric\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "F:\Lorafabric\sd-scripts\train_network.py", line 272, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "F:\Lorafabric\sd-scripts\library\train_util.py", line 2080, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "F:\Lorafabric\sd-scripts\library\train_util.py", line 1023, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "F:\Lorafabric\sd-scripts\library\train_util.py", line 2428, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: F:\Lorafabric\dataset\2_38\056.jpg
Traceback (most recent call last):
  File "C:\Users\solid\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\solid\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Lorafabric\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Lorafabric\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "F:\Lorafabric\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "F:\Lorafabric\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\Lorafabric\\sd-scripts\\venv\\Scripts\\python.exe', 'sdxl_train_network.py', '--pretrained_model_name_or_path', 'F:\\StabilityMatrix-win-x64\\Data\\Models\\StableDiffusion\\ponyDiffusionV6XL_v6StartWithThisOne.safetensors', '--train_data_dir', 'F:\\Lorafabric\\dataset', '--output_dir', 'F:\\Lorafabric', '--network_module', 'networks.lora', '--xformers', '--gradient_checkpointing', '--persistent_data_loader_workers', '--no_metadata', '--cache_latents', '--cache_latents_to_disk', '--max_data_loader_n_workers', '1', '--enable_bucket', '--save_model_as', 'safetensors', '--lr_scheduler_num_cycles', '4', '--mixed_precision', 'fp16', '--learning_rate', '0.0001', '--resolution', '1024', '--train_batch_size', '2', '--max_train_epochs', '6', '--network_dim', '8', '--network_alpha', '2', '--shuffle_caption', '--keep_tokens', '1', '--optimizer_type', 'Lion', '--lr_warmup_steps', '100', '--output_name', 'pony', '--vae', 'F:\\StabilityMatrix-win-x64\\Data\\Models\\VAE\\sdxl_vae.safetensors', '--save_precision', 'fp16', '--lr_scheduler', 'cosine_with_restarts', '--min_bucket_reso', '512', '--max_bucket_reso', '2048', '--caption_extension', '.txt', '--seed', '42', '--logging_dir', 'F:\\Lorafabric', '--loss_type', 'l2', '--huber_schedule', 'snr']' returned non-zero exit status 1.

(venv) F:\Lorafabric\sd-scripts>

**Comment by RedRayz** [comment]
latentキャッシュ(VAEのエンコード)中にNaN演算が発生したことが原因であり、GUI側の問題ではありません。
以下の方法で解決しますのでお試しください。
詳細設定->VAEを32ビットで使用をオンにするか、VAEに[こちら](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix)で配布されているものを指定します。

**Comment by ttyksi** [comment]
ありがとうございます🙇
